services:
  - type: web
    name: solana-http-server
    runtime: rust
    buildCommand: "cargo build --release"
    startCommand: "./target/release/solana-http-server"
    plan: free
    envVars:
      - key: PORT
        value: 3000
